# src/AppBundle/Resources/config/routing.yml

# ===================================================== #
#                                                       #
# #################### FRONT END ###################### #
#                                                       #
# ===================================================== #

front_home:
    path:      /
    defaults: { _controller: AppBundle:Front:home }

security_login:
    path:      /login
    defaults: { _controller: AppBundle:Security:login }

security_logout:
    path:      /logout
    defaults: { _controller: AppBundle:Security:logout }

security__register:
    path:      /register
    defaults: { _controller: AppBundle:Security:register }

front_add_trick:
    path:      /trick/add
    defaults: { _controller: AppBundle:Front:addTrick }