# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    # Doctrine listeners
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.save_avatar_listener:
        class: AppBundle\Doctrine\SaveAvatarListener
        arguments:
          - '%kernel.root_dir%'
          - '%path_to_avatars%'
          - '@app.imageresizer'
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.handle_trick_media_listener:
        class: AppBundle\Doctrine\HandleTrickMediaListener
        arguments:
            - '%kernel.root_dir%'
            - '%path_to_trick_images%'
            - '@app.imageresizer'
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.updated_at_listener:
        class: AppBundle\Doctrine\UpdatedAtListener
        tags:
            - { name: doctrine.event_subscriber }

    # Form validators
    validator.user_email_exists:
        class: AppBundle\Validator\Constraints\UserEmailExistsValidator
        autowire: true
        tags:
            - { name: validator.constraint_validator }

    validator.is_user_password:
        class: AppBundle\Validator\Constraints\IsUserPasswordValidator
        autowire: true
        tags:
            - { name: validator.constraint_validator }

    # Other services
    app.mailer:
        class: AppBundle\Services\MailHandler
        public: true
        autowire: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    app.imageresizer:
        class: AppBundle\Services\ImageResizer
        public: true

    app.form.manage.trick:
        class: AppBundle\Form\Trick\ManageTrickForm
        autowire: true